# Generated by Django 2.2.1 on 2019-05-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(default=2019, max_length=100),
            preserve_default=False,
        ),
    ]
