# Generated by Django 2.2.1 on 2019-05-31 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='g', max_length=500),
            preserve_default=False,
        ),
    ]
