# Generated by Django 2.2.1 on 2019-05-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_movie_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
