# Generated by Django 2.2.1 on 2019-05-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='source',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
