# Generated by Django 2.2.1 on 2019-05-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_rating_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='value',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
