# Generated by Django 2.2.1 on 2019-05-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_rating_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='metascore',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
