# Generated by Django 2.2.1 on 2019-05-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_movie_metascore'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdbrating',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
