# Generated by Django 2.2.1 on 2019-05-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_movie_imdbrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdbvotes',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
