# Generated by Django 2.2.1 on 2019-05-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_movie_imdbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
