# Generated by Django 2.2.1 on 2019-05-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_movie_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='totalseasons',
            field=models.SmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
