# Generated by Django 2.2.1 on 2019-05-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_movie_totalseasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='totalseasons',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
