# Generated by Django 2.2.1 on 2019-05-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0030_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
